.TH fmsplay 1 "February 16, 2022" "" "libfmsynth"
.SH NAME
fmsplay
.SH SYNOPSIS
fmsplay [OPTION...] <filename>
.SH DESCRIPTION
Playback libfmsynth blueprint files.

Usage:
  fmsplay [OPTION...] <filename>

  -v, --verbose                 Verbose mode.
  -s, --samples-per-second arg  Set samples per second. Use 0 for maximum
                                possible.
  -o, --output arg              Write to file in WAV format.
  -h, --help                    Print help.
.SH "SEE ALSO"
https://github.com/Peanhua/libfmsynth
